[build]
  publish = "dist/"
  command = "yarn build-netlify"
  functions = "functions"

# These build env vars are specific only to Netlify.
[build.environment]
  YARN_VERSION = "3.2.1"
  CI = "true"

[functions]
  directory = "src/functions"
