[build]
  command = "REACT_APP_HOST='netlify' REACT_APP_NETLIFY_CONTEXT=$CONTEXT REACT_APP_NETLIFY_BUILD_ID=$BUILD_ID REACT_APP_GIT_BRANCH=$BRANCH REACT_APP_GIT_COMMIT_REF=$COMMIT_REF REACT_APP_GIT_REVIEW_ID yarn build"