export const bipsList = [
  { path: '/Bips/bip-0.html', title: 'Silo Refactor' },
  { path: '/Bips/bip-1.html', title: 'First Budget' },
  { path: '/Bips/bip-2.html', title: 'Tax Efficiency & Weather' },
  { path: '/Bips/bip-3.html', title: 'Capital Formation Advisor Budget' },
  { path: '/Bips/bip-4.html', title: 'Trail of Bits Audit and FundraiserFacet' },
  { path: '/Bips/bip-5.html', title: 'Omniscia Audit' },
  { path: '/Bips/bip-6.html', title: 'Soil Efficiency' },
  { path: '/Bips/bip-7.html', title: 'Expanded Convert' },
  { path: '/Bips/bip-8.html', title: 'Beanstalk Q1 Budget' },
  { path: '/Bips/bip-9.html', title: 'Various Efficiency Improvements' },
  { path: '/Bips/bip-10.html', title: 'Omniscia Retainer' },
  { path: '/Bips/bip-11.html', title: 'Farmers Market' },
  { path: '/Bips/bip-12.html', title: 'Silo Generalization I' },
  { path: '/Bips/bip-13.html', title: 'Adjustment to Weather Changes' },
  { path: '/Bips/bip-14.html', title: 'Beanstalk Q2 2022 Budget' },
];
