export { default as Page } from './Page';
export { default as FarmPage } from './FarmPage';
export { default as AnalyticsPage } from './AnalyticsPage';
export { default as DAOPage } from './DAOPage';
export { default as BeaNFTPage } from './BeaNFTPage';
export { default as AboutPage } from './AboutPage';
export { default as FundraiserPage } from './FundraiserPage';
export { default as MetamasklessPage } from './MetamasklessPage';
export { default as SiloPage } from './SiloPage';